extends: airbnb
rules:
  no-console:
    off
  react/jsx-filename-extension:
    off
  react/no-array-index-key:
    off
  jsx-a11y/anchor-is-valid:
    off
  react/no-did-mount-set-state:
    off
  react/forbid-prop-types:
    off
  react/require-default-props:
    off
globals:
  fetch: false
  document: false